server:
  port: ${PORT:8080}
  servlet:
    context-path: /

spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  web:
    resources:
      static-locations: classpath:/static
  datasource:
    url: jdbc:sqlite:debtors.db
    driver-class-name: org.sqlite.JDBC
  jpa:
    hibernate:
      database-platform: org.hibernate.community.dialect.SQLiteDialect
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true